import { Card } from "@/components/ui/card";
import { TrendingUp, Shield, Users, Brain, AlertCircle, BarChart2 } from "lucide-react";

const Features = () => {
  const features = [
    {
      icon: TrendingUp,
      title: "PREDICT",
      subtitle: "RISK",
      description: "AI-driven risk prediction through Deep Learning models",
      details: ["Early warning alerts for high-risk scenarios", "Predictive analytics based on historical data", "Real-time risk assessment"],
      gradient: "from-primary/20 to-primary/10",
      iconBg: "bg-gradient-to-br from-primary to-primary-glow"
    },
    {
      icon: AlertCircle,
      title: "PREVENT", 
      subtitle: "ACCIDENT",
      description: "Through advanced data-driven analytics",
      details: ["Proactive safety suggestions and action plans generated by AI", "Automated compliance monitoring", "Preventive maintenance scheduling"],
      gradient: "from-warning-amber/20 to-warning-amber/10",
      iconBg: "bg-gradient-to-br from-warning-amber to-safety-orange"
    },
    {
      icon: Shield,
      title: "PROTECT",
      subtitle: "PEOPLE", 
      description: "Revolutionary SAFETY SCORE algorithm for accountability",
      details: ["Digital incident logging and monitoring", "Integrated RIDDOR compliant reporting", "Real-time safety performance tracking"],
      gradient: "from-safety-orange/20 to-safety-orange/10",
      iconBg: "bg-gradient-to-br from-safety-orange to-destructive"
    }
  ];

  return (
    <section className="py-20 bg-muted/30">
      <div className="container">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Comprehensive Workplace Safety
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Our AI-powered platform combines prediction, prevention, and protection to create 
            the safest possible work environment for your team.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8 max-w-7xl mx-auto">
          {features.map((feature, index) => (
            <Card key={index} className="relative p-8 border-0 shadow-lg hover:shadow-xl transition-all duration-300 group">
              {/* Background gradient */}
              <div className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} rounded-lg opacity-50 group-hover:opacity-70 transition-opacity`} />
              
              <div className="relative z-10">
                {/* Icon */}
                <div className={`w-20 h-20 rounded-full ${feature.iconBg} flex items-center justify-center mb-6 mx-auto shadow-lg`}>
                  <feature.icon className="w-10 h-10 text-white" />
                </div>

                {/* Title */}
                <div className="text-center mb-6">
                  <h3 className="text-2xl font-bold mb-1">{feature.title}</h3>
                  <p className="text-lg text-muted-foreground font-medium">{feature.subtitle}</p>
                </div>

                {/* Description */}
                <p className="text-center text-muted-foreground mb-6 leading-relaxed">
                  {feature.description}
                </p>

                {/* Feature list */}
                <ul className="space-y-3">
                  {feature.details.map((detail, detailIndex) => (
                    <li key={detailIndex} className="flex items-start text-sm text-muted-foreground">
                      <div className="w-2 h-2 rounded-full bg-primary mt-2 mr-3 flex-shrink-0" />
                      {detail}
                    </li>
                  ))}
                </ul>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;